turbine:
  radius_mode: manual
  r: 35.0 #diameter
  H: 1.0
  twist: 0.0
  delta: 0.0
  chord:
  - 1.75
  B: 2
  solidity: # Calculated based on diameter
  - 0.1
  centerX: 0
  centerY: 0
  Omega: 1.427
  ntheta: 36
environment:
  Vinf:
  - 6.23 #parametro variado no experimento de sanvito
  rho: 1.225
  mu: 1.7894e-05
simulation:
  fixed_parameter: vinf
  num_turbines: 1
  airfoil:
  - naca0018
  Re: 300000
  Mach: 0.3
  include_360_deg_effects: false
  var_omega_vinf: 1

  simulation3d:
    enabled: true
    height: 3.0 
    n_slices: 20
    velocity_profile: power_law # constant or power_law
    tip_loss: false #true: on; false: off
    discretization_power: 1 # 1: linear, 2: power law
aero:
  method: neuralfoil
  model_size: large
  file: src/data/experimental/NACA_0012_mod.dat
  dynamic_stall: true
output:
  save: false
  save_config: false
  save_plot: false
  data_file:
    format: dat
    include_header: true
  plot_image:
    format: png
    dpi: 300
flow_curvature:
  enabled: true
  normalized_hook_point: 0.1
