# ==============================================================================
# PyVAWT Configuration File for Multiple Turbine Simulation
# ==============================================================================

turbine:
  r: 35.0                         # Rotor radius (m)
  twist: 0.0                     # Blade twist angle (rad)
  delta: 0.0                     # Pre-set pitch angle (rad)
  chord: 1.75                    # Blade chord length (m)
  B: 2                           # Number of blades
  solidity: 0.1                 # Rotor solidity
  centerX: [0.0, 140.0, 280.0]     # X coordinates of the center of each turbine (m)
  centerY: [0.0, 0.0, 0.0]       # Y coordinates of the center of each turbine (m)
  Omega: 1.427                     # Initial angular velocity (rad/s)
  ntheta: 36                     # Azimuthal discretization (number of steps)

environment:
  Vinf: 6.23                      # Free-stream wind velocity upstream (m/s)
  rho: 1.225                     # Air density (kg/m³)
  mu: 1.7894e-5                  # Air dynamic viscosity (Pa.s)

solver:
  num_turbines: 3                # Number of coupled turbines in the simulation
  method: neuralfoil             # "neuralfoil" or "file". It's the way the cl and cd is obtained.
  fixed_parameter: vinf         # "omega" or "vinf"

  neuralfoil:
    airfoil: naca0018            # Airfoil profile designated for the simulation
    model_size: large            # "xxsmall"	"xsmall"	"small"	"medium"	"large"	"xlarge"	"xxlarge"	"xxxlarge"

  file:
    path: src/data/experimental/NACA_0012_mod.dat   # Path to polar data file

output:
  save: true                     # Save simulation results
  save_config: true              # Save a copy of this configuration file with the results
  save_plot: true                # Generate and save output plots

  data_file:
    format: dat                  # Output data file format: "dat" or "csv"
    include_header: true         # Include column headers in the output file

  plot_image:
    format: png                  # Output plot image format: "png" or "eps"
    dpi: 300                     # Image resolution (Dots Per Inch)
