turbine:
  radius_mode: manual
  r: 1.51
  H: 1.0
  twist: 0.0
  delta: 0.0
  chord:
  - 0.086
  B: 3
  solidity:
  - 0.38
  centerX: 0
  centerY: 0
  Omega: 41.89
  ntheta: 36
environment:
  Vinf:
  - 0.1
  rho: 1.225
  mu: 1.7894e-05
simulation:
  fixed_parameter: omega
  num_turbines: 1
  airfoil:
  - naca0021
  Re: 300000
  Mach: 0.3
  include_360_deg_effects: false
  var_omega_vinf: 1
aero:
  method: neuralfoil
  model_size: xxxlarge
  file: src/data/experimental/NACA_0012_mod.dat
output:
  save: true
  save_config: true
  save_plot: true
  data_file:
    format: dat
    include_header: true
  plot_image:
    format: png
    dpi: 300
flow_curvature:
  enabled: true
  normalized_hook_point: 0.1
