[project]
name = "pyvawt"
version = "0.3.0"
description = "Simulation of vertical-axis wind turbines using the actuator cylinder method."
readme = "README.md"
requires-python = ">=3.13"
license = {text = "MIT"}
dependencies = [
    "h5py>=3.13.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
    "typing>=3.10.0.0",
]
